### ISSUE TITLE
Lesson 2.08  zork.py not found

### ISSUE THREAD

**Issue by normanbauer** [TEALS-IntroCS/2nd-semester-introduction-to-computer-science-principles#53]
There is no file for zork.py

**Comment by goldblatt** [comment]
okay so this is a gitbook issue-- it exists in the github, but since the file is type .py gitbook can't convert it into html and it doesn't display. I can change all the files to be .md which will allow it show up in the gitbook, but i think we probably don't want these files in the gitbook and would prefer that they are actual python files.

**Comment by goldblatt** [comment]
sorry didn't mean to close

**Comment by normanbauer** [comment]
Could you put it in another repository and link to it?

**Comment by TEALS-IntroCS** [comment]
This will be solved by #46
