### ISSUE TITLE
Cloud9, ChromeBook and Piazza compatibility

### ISSUE THREAD

**Issue by normanbauer** [TEALS-IntroCS/2nd-semester-introduction-to-computer-science-principles#86]
I saw where Cloud9 was ChromeBook compatible. Using the ChromeBook, could you download the Python file to the ChromeBook and then submit it to piazza using the downloaded file?

**Comment by TEALS-IntroCS** [comment]
This isn't an actionable curriculum bug... 
A quick web search suggests that Chromebooks can handle downloading/uploading and basic file manipulation: https://support.google.com/chromebook/answer/1700055?hl=en

Files can also be saved to Google Drive.

I'd suggest trying this with a Chromebook, or asking about this on Piazza since there are lots of folks there with access to Chromebooks. 

The "IDE Set Up" document in lesson 1 suggests that each student share their Cloud9 workspace with the teacher's account, so the teacher gets access to their files for submission/grading.

**Comment by normanbauer** [comment]
The reason I asked was a financial one.  The ChromeBooks are much more affordable than PCs or Macs, but you give up capability. If the Intro and/or the AP class could run effectively on the ChromeBook, it would be a very good selling point, especially if TEALS could negotiate a special school price with Google/manufacturer. I am meeting today (Jan 11) with Dr. Shannon, STEM director for the Synergy schools.  We are going to discuss the future direction of computer science at the Synergy schools, in particular the second semester course for intro. She listened to your presentation last week.
